#ifndef KEYS_H
#define KEYS_H

#define DOSK_1                2
#define DOSK_2                3
#define DOSK_3                4
#define DOSK_4                5
#define DOSK_5                6
#define DOSK_6                7
#define DOSK_7                8
#define DOSK_8                9
#define DOSK_9                10
#define DOSK_0                11
#define DOSK_MINUS            12
#define DOSK_EQUALS           13
#define DOSK_BKSP             14
#define DOSK_Q                16
#define DOSK_W                17
#define DOSK_E                18
#define DOSK_R                19
#define DOSK_T                20
#define DOSK_Y                21
#define DOSK_U                22
#define DOSK_I                23
#define DOSK_O                24
#define DOSK_P                25
#define DOSK_LFT_BRACKET      26
#define DOSK_RGT_BRACKET      27
#define DOSK_A                30
#define DOSK_S                31
#define DOSK_D                32
#define DOSK_F                33
#define DOSK_G                34
#define DOSK_H                35
#define DOSK_J                36
#define DOSK_K                37
#define DOSK_L                38
#define DOSK_SEMI             39
#define DOSK_APOS             40
#define DOSK_TILDE            41
#define DOSK_LEFT_SHIFT       42
#define DOSK_BACK_SLASH       43
#define DOSK_Z                44
#define DOSK_X                45
#define DOSK_C                46
#define DOSK_V                47
#define DOSK_B                48
#define DOSK_N                49
#define DOSK_M                50
#define DOSK_COMMA            51
#define DOSK_PERIOD           52
#define DOSK_FOWARD_SLASH     53
#define DOSK_RIGHT_SHIFT      54
#define DOSK_PRT_SCRN         55
#define DOSK_CAPS_LOCK        58
#define DOSK_F1               59
#define DOSK_F2               60
#define DOSK_F3               61
#define DOSK_F4               62
#define DOSK_F5               63
#define DOSK_F6               64
#define DOSK_F7               65
#define DOSK_F8               66
#define DOSK_F9               67
#define DOSK_F10              68
#define DOSK_F11              87
#define DOSK_F12              88
#define DOSK_NUM_LOCK         69
#define DOSK_SCROLL_LOCK      70
#define DOSK_HOME             71
#define DOSK_PGUP             73
#define DOSK_KEYPAD_MINUS     74
#define DOSK_CENTER           76
#define DOSK_KEYPAD_PLUS      78
#define DOSK_END              79
#define DOSK_PGDWN            81
#define DOSK_INS              82
#define DOSK_DEL              83
#define DOSK_RIGHT      77
#define DOSK_LEFT       75
#define DOSK_UP         72
#define DOSK_DOWN       80
#define DOSK_ENTER      28
#define DOSK_TAB        15
#define DOSK_SPACE      57
#define DOSK_CTRL       29
#define DOSK_ALT        56
#define DOSK_ESC        1

#endif // KEYS _H
